services:
  gatus:
    image: twinproduction/gatus
    ports:
      - "9090:8080"
    environment:
      GATUS_CONFIG_PATH: "/config/config.yaml"
    volumes:
      - "./config:/config"

  test-1:
    image: curlimages/curl
    volumes:
      - "./scripts:/scripts"
    entrypoint: ["/scripts/test1.sh"]
      
  test-2:
    image: curlimages/curl
    volumes:
      - "./scripts:/scripts"
    entrypoint: ["/scripts/test2.sh"]
